### ISSUE TITLE
What to do if heroku app gets suspended?

### ISSUE THREAD

**Issue by oneironaut2209** [ksssomesh12/tg-mirror-bot#1]

**Comment by ksssomesh12** [comment]
can u be little more specific? why does the app got suspended? personally, i have been using the app on heroku for almost two months and so far i ve had no issues.

**Comment by oneironaut2209** [comment]
2 mins after deploying it gets suspended without any reason, I just started the bot thats it.

**Comment by ksssomesh12** [comment]
post the bot log / heroku app log here. it might be of some help

**Comment by oneironaut2209** [comment]
The bot is working now without suspension.

**Comment by ksssomesh12** [comment]
if the bot gets suspended, attach the log or related info that would help diagnosing the issue

**Comment by oneironaut2209** [comment]
I used another repo thats why it got suspend , now with your repo its working awesome

**Comment by ksssomesh12** [comment]
From that another repo, did u deploy manually or with the  'deploy to heroku' button?

**Comment by oneironaut2209** [comment]
It was the original repo from where you did pull request. I did everything manually with git/heroku-cli and repl.it on windows.

**Comment by ksssomesh12** [comment]
ur bot deployed using lzzy12/python-aria-mirror-bot repo got suspended on heroku?

**Comment by oneironaut2209** [comment]
Yes that one. Your one is working fine. What did you changed that heroku is not suspending the app?

**Comment by ksssomesh12** [comment]
I don't think I changed anything regarding the bot being suspended by heroku. So, the real question, why my repo just works fine and lzzy12's doesn't is because, maybe I guess, simply due to the fact that, this is a different repo and does not have much deploys like lzzy12's which has many deploys on heroku already, maybe they have some rate limiting based on the repo info, by which the newer bots are suspended. By 'newer', I mean that the older boys deployed with lzzy12's repo works just fine or that's what I hear from people.
