### ISSUE TITLE
If there are no active downloads then will the bot sleep in 30mins or not?

### ISSUE THREAD

**Issue by oneironaut2209** [ksssomesh12/tg-mirror-bot#4]
I am using free dynos so should I keep worker on always 24/7 ?

**Comment by ksssomesh12** [comment]
from my experience, the bot doesnt sleep automatically as mentioned in heroku docs. n also there are only 550 free dyno hours for an account and 450 more dyno hours if u have added ur credit card to the billing. so do the math and my advice is not to keep worker up always

[Apps that have more than 1 web dyno running never go to sleep and worker dynos (or other process types) are never put to sleep.](https://blog.heroku.com/app_sleeping_on_heroku)
[Apps that only utilise a free worker dyno do not sleep, because they do not respond to web requests. Be mindful of this as they may run 24/7 and consume from your pool of hours](https://devcenter.heroku.com/articles/free-dyno-hours)

**Comment by ksssomesh12** [comment]
[Apps that have more than 1 web dyno running never go to sleep and worker dynos (or other process types) are never put to sleep.](https://blog.heroku.com/app_sleeping_on_heroku)

**Comment by oneironaut2209** [comment]
450 more hours are onetime or monthly (550+450 = 1000 = 42days) If they give extra 450 hrs per month then we can keep it always on?

**Comment by ksssomesh12** [comment]
free dynos are replenished at the start of every month. yes if u have 1000 dyno hours and only 1 app worker process to run, you can run it 24x7, ie, keep it always on

**Comment by oneironaut2209** [comment]
Best option is to schedule it to work at day and turned off at night (if 550 hours??) . And do you keep it always on? 

Mega links not working btw.

**Comment by ksssomesh12** [comment]
If its 550 hours, best option is to schedule it in whatever way the owner might prefer it too.
I dont keep it always on. I only turn it on when i want to dl stuff and in case, if the remaining dyno hours is enough to suffice for the rest of the days until the end of the month, then i wont bother to turn it off.
Well, mega-dl not working is a known issue as of now.
Its very unstable at the moment. Dont hope for it to be fixed anytime soon.

**Comment by ksssomesh12** [comment]
> Best option is to schedule it to work at day and turned off at night (if 550 hours??) . And do you keep it always on?
> 
> Mega links not working btw.

Check out the 'dev' branch. MEGA links are completely working now

**Comment by oneironaut2209** [comment]
Ok I will try today 👍
